---
title: "latex-math Macros"
output: 
  pdf_document:
    keep_tex: TRUE
header-includes:
   - \usepackage{mathtools}
   - \usepackage{siunitx}
   - \usepackage{dsfont}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
library(xtable)
```

```{r get-macros, echo = FALSE}
sanitize_command <- function(command) {
  command <- stringr::str_replace_all(
    command, 
    pattern = "#([1-9])",
    replacement = "arg\\1")
}
get_command <- function(line) {
  command <- regmatches(line, gregexpr("\\{(?>[^{}]|(?R))*\\}", line, perl=TRUE))[[1]]
  if (length(command)) != 2) return(NULL)
  command[3] <- str_extract(line, pattern = "\\}\\s*%\\s*(.*)$")
  names(command) <- c("Macro", "Notation", "Comment")
  command[1] <- paste0("\\verb!", command[1], "!")
  command[2] <- paste0("$", sanitize_command(command[2]), "$")
  command
}

line <- macros[[1]][29]

c(regmatches(line, gregexpr("\\{(?>[^{}]|(?R))*\\}", line, perl=TRUE))

str_match(line, "")
str_match(line, pattern = "\\{(R)\\}")

rex("\\((?>[^()]|(?R))*\\)")

macros <- list.files(pattern = "\\.tex$") %>% 
  map(~ readLines(.)) %>% 
  map_depth(.depth = 2, ~ get_command(.)) %>% 
  map(~ discard(., .p = is.null) %>% 
        do.call(rbind, .)) 
names(macros) <- list.files(pattern = "\\.tex$")
```

```{r print-macros, results='asis', echo = FALSE, }
for (i in seq_along(macros)) {
  cat("\\section{",  names(macros)[i], "}")
  print(knitr::kable(macros[[i]]))
}

```
